### PR TITLE
depend not on grpc-all, but on more fine-grained dependencies

### LINKED ISSUE #113: grpc should not depend on grpc-all
1) It will be removed: https://github.com/grpc/grpc-java/issues/1597
2) It repackages classes for everything making navigation to sources in IDE a pain.

Proposal for fix: runtime should depend on grpc-stub, tests should depend on grpc-netty.

### PR DESCRIPTION
**Pull request by eiennohito**
fixes #113 

Need to fix docs as well by introducing explicit dependency on a transport, otherwise default examples will stop working.

### CODE REVIEW

**Comment by eiennohito** [comment]
oops, forgot to fix e2e

**Comment by thesamet** [comment]
Thanks for working on this. Can you also submit a PR for the docs as well (via the gh-pages branch) and to the reference example at https://github.com/xuwei-k/grpc-scala-sample ?

**Comment by eiennohito** [comment]
All right

**Comment by eiennohito** [comment]
Okay, seems to be done.

In the example project I have updated ScalPB dependency to 0.5.27, so it should be merged after the next release.

**Comment by xuwei-k** [comment]
👍

**Pull request merged**
