### PR TITLE
Add companion_extends

### LINKED ISSUE #105: Option for companion objects to extend specified classes/traits
I know currently we have the option to extend generated classes with custom super classes/traits:

```protobuf
message MyMessage {
  option (scalapb.message).extends = "MySuperClass";
  int32 dummy = 999;
}
```

However, I often find myself wanting to extend generated companion objects with custom super classes/traits, maybe something like that will help:

```protobuf
message MyMessage {
  option (scalapb.message).extends = "MySuperClass";
  option (scalapb.message).companion_extends = "MySuperCompanionClass";
  int32 dummy = 999;
}
```

Please let me know if this would align with your roadmap. I'm happy to submit a PR. Thanks.

### PR DESCRIPTION
**Pull request by ngthanhtrung**
This PR would fix #105. Please help me review, thanks.

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for working on this. It looks good overall, except that the autogenerated Java file seem to have been generated with a different version of protoc. Can you use the latest protoc, protoc 3.0.0-beta2, to generate them?

**Comment by ngthanhtrung** [comment]
Updated! *protoc 3.0.0-beta2* is used now.

**Comment by thesamet** [comment]
Merged - thanks for contributing this.

**Comment by ngthanhtrung** [comment]
Could you publish a new version of *ScalaPB*? Or do you have any ETA for it?

**Comment by ngbinh** [comment]
👍  on a new release

**Comment by thesamet** [comment]
Yes - released 0.5.26.

**Pull request merged**
